### ISSUE TITLE
Missing dependency `markdown` during `setup.py`.

### ISSUE THREAD

**Issue by wapiflapi** [kriberg/esy#2]
When installing this package using `python setup.py install` I had a problem because the `markdown` package is required but wasn't installed in my venv. I would have submitted a PR, but I'm not sure on the best way to fix this because I don't think simply adding it to the `requirements.txt` will solve the problem as this issue arrises during install, before those dependencies are installed.

The only solution I see for the moment is to manually implement what `markdown` is used for if that is really important. Any thoughts and other ideas?

**Comment by kriberg** [comment]
I should just remove the markdown parsing from setup.py. Shouldn't depend on any external requirements to run setup. I _think_ I was trying to save myself hassle by importing the description.

**Comment by wapiflapi** [comment]
34cb020d37e5cee578e1a6c82be2811ded118df7 fixes this. Thanks!
